[package]
name = "server"
version = "0.1.0"
authors = ["ebosi38051 <ebosi38051@gmail.com>"]

[dependencies]
rocket = "0.3.11"
rocket_codegen = "0.3.11"
rocket_contrib = "0.3.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
