// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("App");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (self) {
      return self[/* state */2][/* page */0];
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* page */React.createElement("div", undefined, "hello")];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* page */action[0]]]);
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
